### ISSUE TITLE
Add array nested

### ISSUE THREAD

**Issue by dankor** [GitRoko/meta-data-editor#17]
If json_type is array. We should check for the key with the same name. For example:

```
topics:
  json_type: array
  mandatory: false
  td_type: varchar
  pydantic_type: List
  array:
    json_type: number
    mandatory: false
    pydantic_type: integer
    example:  someText
```

```
topics:
  json_type: array
  mandatory: false
  td_type: varchar
  pydantic_type: List
  example:
    - someText
```

If array there, you have to render sub-field:
![image](https://user-images.githubusercontent.com/1557077/173564396-4d6258f7-6ef3-4b73-aaeb-4b38f38d6aef.png)
Sorry for wrong layout. You should make a bit nicer. :confused: 
Acceptance criteria:
1. Nested toggle should appear next to Type select if you picked array.
2. If nested activated (array key provided), Example should disappear from UI and remover from the yaml on the parent level
3. If nested deactivated (array key not provided), all sub-elements should disappear and Example appear once again.
4. Sub element shouldn't contain field name. 
5. Sub element shouldn't contain TD type. 
6. Sub element shouldn't contain ± button.
