### ISSUE TITLE
Add object nested

### ISSUE THREAD

**Issue by dankor** [GitRoko/meta-data-editor#20]
If json_type is object. We should check for the key with the same name. For example:

```
topics:
  json_type: object
  mandatory: false
  td_type: varchar
  pydantic_type: Dict
  object:
    id:
      json_type: number
      mandatory: true
      pydantic_type: StrictInt
      example:  123
    name:
      json_type: string
      mandatory: false
      pydantic_type: StrictStr
      example:  abc
```

```
topics:
  json_type: object
  mandatory: false
  td_type: varchar
  pydantic_type: Dict
  example:
    id: 111
    name: abc
```

Acceptance criteria:
1. Nested toggle should appear next to Type select if you picked object.
2. If nested activated (object key provided), Example should disappear from UI and remover from the yaml on the parent level
3. If nested deactivated (object key not provided), all sub-elements should disappear and Example appear once again.
4. Sub element shouldn't contain TD type. 
5. ± should work in the same way, but on the sub level.
![image](https://user-images.githubusercontent.com/1557077/174348719-ffdc71ef-8d55-4fbc-b46d-e102700e0bdd.png)
