### ISSUE TITLE
Generete file from example

### ISSUE THREAD

**Issue by dankor** [GitRoko/meta-data-editor#33]
There should be two options to create a file:

- Blank (old file adding)
- Using JSON example

Let's assume these options are tabs:

- Blank will provide text entry and dropdown
- Example will provide the same plus a multiline text entry

Also, there should be buttons: **Cancel** and **Add**.

The multiline text entry should be validated as a json. It should be a JSON object. 

After pressing "Add" in Example mode will generate fields in the following way:
Filed name -> **JSON key**
Type -> **JSON value** data type
Td type -> the default value from **JSON value** data type
Pydantic type -> the default value from **JSON value** data type
Example -> **JSON value**
Description -> TBD (hardcoded)
Mandatory -> true (hardcoded)
PII -> false (hardcoded)
Fake.type -> enum
Fake.values -> [**JSON value**]

Input example:
```json
{
  "id": 1,
  "name": "Roman",
  "active": true
}
```

Output example:
```yaml
# TBD

id:
  json_type: number
  td_type: bigint
  mandatory: true
  pydantic_type: StrictInt
  example: 1
  faker:
    type: enum
    values:
    - 1
  pii: false
  description: TBD
name:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: Roman
  faker:
    type: enum
    values:
    - Roman
  pii: false
  description: TBD
active:
  json_type: boolean
  td_type: varchar
  mandatory: true
  pydantic_type: StrictBool
  example: true
  faker:
    type: enum
    values:
    - true
  pii: false
  description: TBD
```
