### ISSUE TITLE
Enum faker validation

### ISSUE THREAD

**Issue by dankor** [GitRoko/meta-data-editor#38]
We need to validate and transform data to the corresponding data type:
![image](https://user-images.githubusercontent.com/1557077/192990313-b81c89c0-593d-4e37-8a09-4c9f5dd1a586.png)
```yaml
default_shipping:
type: enum
  values:
    - 'true'
    - 'false'
```

If json_type is bool we should validate enum values as well (the same we do for example).
