### ISSUE TITLE
FormTemplate: Null value guess

### ISSUE THREAD

**Issue by dankor** [GitRoko/meta-data-editor#42]
if there is a null value, please guess by the following logic:
```yaml
{key-name}:
  json_type: string
  td_type: varchar
  mandatory: false
  pydantic_type: StrictStr
  example: null
  faker:
    type: enum
    values:
    - null
  pii: false
  description: TBD
```
